#ifndef SMARTAC_ESP32_CONTROLLER_SECRETS_H
#define SMARTAC_ESP32_CONTROLLER_SECRETS_H

#define WIFI_SSID "MY_WIFI_SSID"
#define WIFI_PASS "MY_WIFI_PASSWORD"
#define MQTT_BROKER "BROKER_IP_ADDRESS"
#define MQTT_PORT 1883

#endif //SMARTAC_ESP32_CONTROLLER_SECRETS_H
