#ifndef FIRMWARE_MQTT_CONNECTION_STATE_H
#define FIRMWARE_MQTT_CONNECTION_STATE_H

enum class MqttConnectionState {
    DISCONNECTED,
    CONNECTING,
    CONNECTED
};

#endif //FIRMWARE_MQTT_CONNECTION_STATE_H
